reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true
use_try_shorthand = true
write_mode = "overwrite"
chain_indent = "Visual"
chain_one_line_max = 80
match_block_trailing_comma = true
normalize_comments = true
wrap_comments = true
