language: cpp
compiler:
    - gcc
before_install:
    - sudo apt-get install valgrind python-yaml libyaml-dev build-essential libssh2-1-dev libarchive-dev clang
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install gcc-4.8 g++-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++
    - sudo update-alternatives --config gcov
    - sudo pip install cpp-coveralls
script:
    - make
    - tar cvf include.tar.gz include/
    - bash test/test-script.sh
after_script:
    - gcov yabs.gcda
    - coveralls --exclude include
    - make clean
    - qmake-qt4 "CONFIG+=clang"
    - make
notifications:
    email:
        recipients:
            - albcoron@gmail.com
            - alberto@0x1a.us
        on_failure: always
        on_success: change
branches:
    only:
        - master
