language: cpp
compiler:
    - gcc
before_install:
    - sudo apt-get install python-yaml libyaml-dev build-essential libssh2-1-dev libarchive-dev
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install gcc-4.8 g++-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++
    - sudo update-alternatives --config gcov
    - sudo pip install cpp-coveralls
script:
    - make
    - tar cvf include.tar.gz include/
    - ./yabs -h
    - ./yabs -n
    - ./yabs -p test/yabs.yml
    - ./yabs -p test/yabs-include.yml
    - ./yabs -d yabs.ybf
    - ./yabs -p yabs.pro
    - ./yabs -p yabs.ybf
    - ./yabs -p test/alias.yml
    - ./yabs -p test/ball_clubs.yml
    - ./yabs -p test/ball_players.yml
    - ./yabs -p test/block_literal.yml
    - ./yabs -p test/bool.yml
    - ./yabs -p test/complex_key.yml
    - ./yabs -p test/csv.yml
    - ./yabs -p test/key-values.yml
    - ./yabs -p test/map_map.yml
    - ./yabs -p test/multi_line_scalar.yml
    - ./yabs -p test/multiple_player_stat.yml
    - ./yabs -p test/plain_scalar.yml
    - ./yabs -p test/player_stat.yml
    - ./yabs -p test/quoted_scalar.yml
    - ./yabs -e include.tar.gz
after_script:
    - gcov yabs.gcda
    - coveralls --exclude include
notifications:
    email:
        recipients:
            - albcoron@gmail.com
        on_failure: always
        on_success: change
branches:
    only:
        - master
