language: cpp
compiler:
    - gcc
before_install:
    - sudo apt-get install libyaml-dev build-essential qt4-qmake libssh2-1-dev
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install gcc-4.8 g++-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++
    - sudo update-alternatives --config gcov
    - sudo pip install cpp-coveralls
script:
    - qmake-qt4 "CONFIG+=g++"
    - make
    - ./yabs -d
    - ./yabs -n
    - ./yabs -h
after_script:
notifications:
    email:
        recipients:
            - albcoron@gmail.com
        on_failure: always
        on_success: change
branches:
    only:
        - master
