[package]
name = "yabs"
version = "0.1.1"
authors = ["Alberto Corona <ac@albertocorona.com>>"]
keywords = ["system", "build", "make"]
description = "Yet another build system"
repository = "https://gitlab.com/0X1A/yabs"
license = "BSD-3-Clause"
readme = "README.md"

[dependencies]
toml = "0.1"
rustc-serialize = "0.3"
walkdir = "0.1"
ansi_term = "0.9"

[dependencies.clap]
version = "2"
features = ["yaml", "color"]

[lib]
name = "util"
path = "lib/lib.rs"

[[bin]]
name = "yabs"
path = "src/main.rs"
test = false
