[linux.project]
name = "yabs"
cflags = ["pipe", "std=c++11", "march=x86-64", "mtune=generic", "O2", "pipe",
	"fprofile-arcs", "fstack-protector", "ftest-coverage", "-param=ssp-buffer-size=4", "Wall"]
clean = ['*.gcno', '*.gcda']
compiler = "g++"
ignore = ['distrib']
inc = ['include', '/usr/include']
lang = "cpp"
libs = ['yaml', 'archive', 'gcov']
os = "linux"
src = [
	'src/dist.cpp',
	'src/gen.cpp',
	'src/interface.cpp',
	'src/decoder.cpp',
	'src/profile.cpp',
	'src/remote.cpp',
	'src/yabs.cpp'
]
target = "yabs"
lib = false
version = "0.1.2"
lflags = ''

[windows.project]
name = "yabs"
cflags = ["pipe", "std=c++11", "march=x86-64", "mtune=generic", "O2", "pipe",
	"fstack-protector", "-param=ssp-buffer-size=4", "Wall"]
compiler = "x86_64-w64-mingw32-g++"
ignore = ['distrib']
inc = ['include', '/usr/include']
lang = "cpp"
libs = ['yaml', 'archive']
os = "linux"
src = [
	'src/dist.cpp',
	'src/gen.cpp',
	'src/interface.cpp',
	'src/decoder.cpp',
	'src/profile.cpp',
	'src/remote.cpp',
	'src/yabs.cpp'
]
target = "yabs"
lib = false
version = "0.1.2"
lflags = ''

[all.install]
prefix = "/usr"


[all.doc]
doc = "doc/yabs.1"
doc-type = "man1"
