[project]
name = "use_static_lib"
version = "0.0.1"
target = ["use_static_lib"]
file-extensions = ["cpp"]
compiler = "g++"
compiler-flags = []
src = [
	"src/main.cpp"
]
libraries = ["yabs_test"]
library-directories = ["../static_lib"]
include = ["../test_lib_src"]
linker-flags = []
ignore = []
before-script = []
after-script = []

[[bin]]
name = "use_static_lib"
path = "./src/main.cpp"
                
